# Generated by Django 3.0.1 on 2022-01-27 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20220125_1750'),
    ]

    operations = [
        migrations.CreateModel(
            name='CheckResume',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.IntegerField()),
                ('statut', models.CharField(max_length=50)),
                ('score', models.FloatField()),
            ],
        ),
    ]
